Lots of miscellaneous changes to RMC

diff --git a/rose-devel-tools/install-boost b/rose-devel-tools/install-boost
--- a/rose-devel-tools/install-boost
+++ b/rose-devel-tools/install-boost
@@ -4,6 +4,7 @@ arg0="${0##*/}"
 
 # boost-1.54 has known bugs that prevent building boost without zlib.
 VERSIONS="1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.50 1.51 1.52 1.53 1.54 1.55 1.56 1.57 1.58 1.59"
+COMPILERS="gcc-4.8 gcc-4.9 llvm-3.5"
 
 
 export RMC_BOOST_BASE="$HOME/GS-CAD/boost"
@@ -72,6 +73,25 @@ BOOST_BUILD_COMMAND_1_57_0="./b2"
 BOOST_BUILD_COMMAND_1_58_0="./b2"
 BOOST_BUILD_COMMAND_1_59_0="./b2"
 
+# The relative name for user-specific config (see "./b2 --debug-configuration")
+BOOST_USERCONFIG_FILE_1_43_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_44_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_45_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_46_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_47_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_48_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_49_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_50_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_51_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_52_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_53_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_54_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_55_0=tools/build/v2/user-config.jam
+BOOST_USERCONFIG_FILE_1_56_0=tools/build/src/user-config.jam
+BOOST_USERCONFIG_FILE_1_57_0=tools/build/src/user-config.jam
+BOOST_USERCONFIG_FILE_1_58_0=tools/build/src/user-config.jam
+BOOST_USERCONFIG_FILE_1_59_0=tools/build/src/user-config.jam
+
 
 libraries() {
     local vs="$1" with_commas="$2"
@@ -90,6 +110,11 @@ iostream_flags() {
 build_command() {
     local vs="$1"
     eval 'echo $BOOST_BUILD_COMMAND_'$vs
+}
+
+user_config_file() {
+    local vs="$1"
+    eval 'echo $BOOST_USERCONFIG_FILE_'$vs
 }
 
 # Boost version string. Converts "1.50" -> "1_50_0"
@@ -126,54 +151,75 @@ is_installed() {
 }
 
 for version in $VERSIONS; do
-    (figlet -c "$version" || banner "$version") 2>/dev/null
+    for compiler in $COMPILERS; do
+	(figlet -c "$version with $compiler" || banner "$version with $compiler") 2>/dev/null
 
-    # Given a couple RMC_* variables, figure out the rest
-    eval $(RMC_BOOST_VERSION="$version" rmc resolve boost)
+	# Given a couple RMC_* variables, figure out the rest
+	eval $(RMC_CXX_NAME="$compiler" RMC_BOOST_VERSION="$version" rmc resolve boost)
 
-    vs=$(boost_version_string "$version")
-    logfile="boost_$vs.log"
-    date >"$logfile"
-    echo "boost-$version ($vs) for $RMC_BOOST_ROOT"
-    echo "log file is " $(realpath "$logfile")
-    if is_installed "$RMC_BOOST_ROOT" 2>/dev/null; then
-	echo "already installed; skipping"
-	echo "already installed; skipping" >>"$logfile"
-	continue
-    fi
-
-    mkdir -p "$TEMPDIR"
-    (
-	set -e
-	cd "$TEMPDIR"
-
-	echo "downloading boost-$version..." >&2
-	tarball="boost_$vs.tar.bz2"
-	get_source "$version" "$tarball"
-	if [ ! -f "$tarball" ]; then
-	    echo "$arg0: couldn't download $tarball" >&2
-	    exit 1
+	vs=$(boost_version_string "$version")
+	logfile="boost-${version}_${RMC_CXX_VENDOR}-${RMC_CXX_VERSION}.log"
+	date >"$logfile"
+	echo "boost-$version ($vs) for $RMC_BOOST_ROOT"
+	echo "log file is " $(realpath "$logfile")
+	if is_installed "$RMC_BOOST_ROOT" 2>/dev/null; then
+	    echo "already installed; skipping"
+	    echo "already installed; skipping" >>"$logfile"
+	    continue
 	fi
 
-	builddir="boost_$vs"
-	echo "unpacking into $builddir..." >&2
-	rm -rf "$builddir"
-	tar xf "$tarball"
-	if [ ! -d "$builddir" ]; then
-	    echo "$arg0: unpacking failed for $tarball into $builddir" >&2
-	    exit 1
-	fi
-	cd "$builddir"
+	mkdir -p "$TEMPDIR"
+	(
+	    set -e
+	    cd "$TEMPDIR"
 
-	echo "bootstrap..." >&2
-	(set -x; ./bootstrap.sh --prefix="$RMC_BOOST_ROOT" --with-libraries=$(libraries "$vs" COMMAS))
+	    # Download
+	    echo "downloading boost-$version..." >&2
+	    tarball="boost_$vs.tar.bz2"
+	    get_source "$version" "$tarball"
+	    if [ ! -f "$tarball" ]; then
+		echo "$arg0: couldn't download $tarball" >&2
+		exit 1
+	    fi
 
-	echo "building..." >&2
-	iosflags=$(iostream_flags "$vs")
-	(set -x; $(build_command "$vs") --prefix="$RMC_BOOST_ROOT" $iosflags)
+	    # Untar
+	    builddir="boost_$vs"
+	    echo "unpacking into $builddir..." >&2
+	    rm -rf "$builddir"
+	    tar xf "$tarball"
+	    if [ ! -d "$builddir" ]; then
+		echo "$arg0: unpacking failed for $tarball into $builddir" >&2
+		exit 1
+	    fi
+	    cd "$builddir"
 
-	echo "installing..." >&2
-	(set -x; $(build_command "$vs") --prefix="$RMC_BOOST_ROOT" $iosflags install)
-	is_installed "$RMC_BOOST_ROOT" || exit 1
-    ) >>"$logfile"
+	    # Configure
+	    user_jam=$(user_config_file "$vs")
+	    toolset="$RMC_CXX_VENDOR"
+	    case "$RMC_CXX_VENDOR" in
+		llvm)
+		    toolset=clang
+		    ;;
+	    esac
+	    echo "using $toolset : $RMC_CXX_VERSION : $RMC_CXX_NAME ;" > "$user_jam"
+	    if [ ! -r "$user_jam" ]; then
+		echo "$arg0: cannot create Boost.Build user Jam file: $user_jam" >&2
+		exit 1
+	    fi
+
+	    # Build
+	    echo "bootstrap..." >&2
+	    (set -x; ./bootstrap.sh --prefix="$RMC_BOOST_ROOT" --with-libraries=$(libraries "$vs" COMMAS))
+
+	    echo "building..." >&2
+	    iosflags=$(iostream_flags "$vs")
+	    (set -x; $(build_command "$vs") --prefix="$RMC_BOOST_ROOT" $iosflags toolset=$toolset -d+2)
+
+	    # Install
+	    echo "installing..." >&2
+	    (set -x; $(build_command "$vs") --prefix="$RMC_BOOST_ROOT" $iosflags toolset=$toolset -d+2 install)
+	    is_installed "$RMC_BOOST_ROOT" || exit 1
+
+	) >>"$logfile"
+    done
 done
